### ISSUE TITLE
Error batch processing points

### ISSUE THREAD

**Issue by kokubadejo** [mheberger/delineator#4]
I'm running the delineator tool on over 300 points in my basin csv, and I get this error after 228 watersheds have been delineated:
`IndexError: index 0 is out of bounds for axis 0 with size 0`

Full snippet of error:
![image](https://github.com/mheberger/delineator/assets/90711306/5554b9cf-5b8a-497b-8db8-1207deedade3)

All the data I'm using is as provided in the README except my basins csv:
[basins.csv](https://github.com/mheberger/delineator/files/12786226/basins.csv)

**Comment by mheberger** [comment]
I see what the issue is. There is some truly bizarre topology going on in
the source data. This is the shape of the unit catchment that your outlet
point landed in. MERIT-Basins is incorrectly saying that there are 2
upstream catchments, but that is not the case.

[image: image.png]

You could get the script to run by changing line 229 in `merit_detailed.py`
from `numpixels = 5000` to `numpixels = 1500` and the script will run and
you will get results but they will be nonsense.

In general, this dataset is not suited for delineating very small
watersheds like this. It also will give poor results in areas that are very
flat or have a lot of hydromodification. It looks like this area of
Southern Ontario is very flat and has extensive drainage ditches. The
source data is just not accurate to capture these kinds of details, and
does not deal well with large lakes. I think your options are to do a
manual delineation on a topo map, or try to find a high-resolution DEM for
the area.

**Comment by mheberger** [comment]
Here is the image of the problematic unit catchment:
![Clipboard01](https://github.com/mheberger/delineator/assets/15746631/bc07db5a-274e-4077-ae02-7a291f65087b)

**Comment by kokubadejo** [comment]
Thank you so much, that worked!
